### ISSUE TITLE
Kite doen't work with WSL

### ISSUE THREAD

**Issue by nyejon** [kiteco/vscode-plugin#266] opened 2020-01-29 21:31 UTC
Hi,

I have Kite installed on Windows, but I can't get the VS Code extension to see the kite server running as I am using WSL. 

Is there a workaround?

**Comment by fengyanghe** [comment] 2020-02-29 09:20
me too

**Comment by CookieLau** [comment] 2020-03-11 18:13
me2, I have reinstalled it in WSL environment for several times but it always alerts "kite: not installed", while it works well in windows environment, sincerely hope you can fix it, thx

**Comment by mrmatos6837** [comment] 2020-04-21 19:19
I'd love that as well.

**Comment by haimat** [comment] 2020-04-23 15:49
Ok so this issue is open for months now.
Is there **any** chance we get WSL support in Kite anytime soon?
Without that It's basically of no use in our case :(

**Comment by rogemus** [comment] 2020-05-15 12:50
Any update on this issue?

**Comment by metalogical** [comment] 2020-06-09 01:54
Duplicate of https://github.com/kiteco/issue-tracker/issues/133 – we'll track it there.

WSL is not a top priority for us right now, but supporting non-Systemd and headless Linux environments are both on our roadmap and necessary for Kite to work on WSL. We don't currently have an estimate on when these features will be ready.

**Closed by metalogical** 2020-06-09 01:54 UTC

**Comment by ToastCoder** [comment] 2020-11-28 08:47
I think logging in to kite will solve the problem. I did that and my problem was resolved.
I logged in through the command 
`~/.local/share/kite/login-user`

**Comment by arxarinze** [comment] 2021-01-22 16:07
install a display server, i use **kali-kex** and it works straight from installation. Also for other wsl distros, u can use : **VcXsrv Windows X Server**
![image](https://user-images.githubusercontent.com/17262432/105514801-395ab480-5cd4-11eb-8e09-02e6def3f65a.png)
![image](https://user-images.githubusercontent.com/17262432/105514850-45df0d00-5cd4-11eb-8640-4bf4a9becc48.png)
