### ISSUE TITLE
WSL Integration being ignored

### ISSUE THREAD

**Issue by tiagoarasilva** [kiteco/vscode-plugin#312] opened 2020-07-09 11:25 UTC
The problem is that Kite always had issues with the open-source community. They never listen, they buy open-source packages and inject ads on them. The community is here to help and the reason why Kite is not being used so often is because it doesn't offer this wsl integration. A lot of devs like me would like to go to VSCode on working environments using windows WSL and kite but we can't because they just don't care at all. The CEO always thinks he knows better than the actual users of the product or potential users. That's why a lot of people opt for Pycharm has it offers what Kite + VSCode does and is widely maintained and used. So, there is that. thank you @kiteco for ignoring us, again and again. 

Apologies for this speech but it looks like it's true. As a user from github mentioned before [here](https://github.com/kiteco/kite-connect-js/issues/39), this could easily solve the problem and would put Kite directly competing with Pycharm and other big ones. I like Kite but I'm limited to it's use so my team is abandoning it as is not worth it.

**Comment by metalogical** [comment] 2020-07-09 16:33
duplicate of #133

**Closed by metalogical** 2020-07-09 16:33 UTC
